### ISSUE TITLE
W.I.P.: create action doesn't work

### ISSUE THREAD

**Issue by Erlemorgaine** [Codaisseur/TicketSystem#11]
## What is your slack name?
Erle

## What is the question you have about your code?
Our code seems to not be creating a new pair object for the current user.

## What is link to your PR?
https://github.com/IrinaOvdii/Pairs/pull/22 

## What is the expected outcome?
current_user has a new pair object in the database, which is visible in the localhost:3000/pairs

## What is the actual outcome?
only the pair objects from the seed file are visible in localhost:3000/pairs

**Comment by arnoFleming** [comment]
since the PR is closed I'm also closing this.
