### ISSUE TITLE
Action creater dispatch doesn't work 

### ISSUE THREAD

**Issue by Mqspx800** [Codaisseur/TicketSystem#14]
## What is your slack name?
Shawn Wu
## What is the question you have about your code?
I tried to make a Thunk action that can add url into state, but it seems the add action doesn't dispatch.
## What is link to your PR?
https://github.com/nicolaurech/dog-project/pull/15
## What is the expected outcome?
the action should add a object with dogs url into the  redux state
## What is the actual outcome?
the action creater is in the state, but calling it do nothing

**Comment by Reinoptland** [comment]
In src/Actions/Game2Actions

You thunk takes the response and returns a new function instead of dispatching an action:

```javascript
export function getRandomDogImage(dog) {
  return function(dispatch){
      request('https://dog.ceo/api/breed/collie/images/random')
      .then(res =>()=>{
        console.log(res.body.message)
        dispatch(setDogImg(res.body.message))
      })
  }
}
```

Should be become: 

```
      .then(res => {
          console.log(res.body.message)
          console.log('RESPONSE?', res)
  
          dispatch(setDogImg(res.body.message))
      })
```
