### ISSUE TITLE
Github pushing my feature branch

### ISSUE THREAD

**Issue by rickhekman** [Codaisseur/TicketSystem#15]
## What is your slack name?
Rick Hekman
## What is the question you have about your code?
First I cloned the new repopisitory and want to push my feature branch, how do I get the correct acces rights? 
## What is link to your PR?
https://github.com/MerylGeugies/DogSpiritAnimal
## What is the expected outcome?
new feature branch on repository
## What is the actual outcome?
fatal: 'origin' does not appear to be git repository
fatal: could new read from remote repository
please make sure you have the correct access rights and the repository exists.

**Comment by Reinoptland** [comment]
.git was deleted by rm -rf .git (to change a branch name)

It was recreated using git init. 

Therefore the origin reference was deleted also.
