### ISSUE TITLE
Help to pass the breed name for other component using redux

### ISSUE THREAD

**Issue by dianadiasds** [Codaisseur/TicketSystem#17]
## What is your slack name?
dianadiasds

## What is the question you have about your code?
I dont now how to pass some props between my component, now that I am using redux

## What is link to your PR?
https://github.com/nicolaurech/dog-project

## What is the expected outcome?
pass de name of the breed in the .get

## What is the actual outcome?
undefined

**Comment by Reinoptland** [comment]
- The props of the dog were passed from React router
- They were found in props.match.params.breed
