### ISSUE TITLE
the state change when a go back to home

### ISSUE THREAD

**Issue by dianadiasds** [Codaisseur/TicketSystem#20]
## What is your slack name?
dianadiasds
## What is the question you have about your code?
how to manage the state of reducer, to receive data from 2 components

## What is link to your PR?
https://github.com/nicolaurech/dog-project/tree/feat/detail-page

## What is the expected outcome?
keep state 

## What is the actual outcome?
the state change when a go back to home

**Comment by Reinoptland** [comment]
Split up the reducer to images & breeds using combinReducers
