### ISSUE TITLE
Class for component

### ISSUE THREAD

**Issue by rickhekman** [Codaisseur/TicketSystem#22]
## What is your slack name?
Rick Hekman
## What is the question you have about your code?
I want to make a component for our buttons, I try to make it with a class, but then I use the reference to the buttons component on a page, and not to a specific button type. How can I approach this in a good way?
Now we only tend to use two buttons, but I am sure we are going to use more buttons.
## What is link to your PR?
https://github.com/MerylGeugies/DogSpiritAnimal
## What is the expected outcome?
reference to verious types of buttons
## What is the actual outcome?
reference to the <Buttons /> component.

**Comment by Reinoptland** [comment]
Use props to make components dynamic
