### ISSUE TITLE
Access current user.id inside the User.rb methods 

### ISSUE THREAD

**Issue by mrjln** [Codaisseur/TicketSystem#8]
## What is your slack name?
mrjln
## What is the question you have about your code?
I cannot acces the user.id attribute inside the methods of user.rb. 
I want to delete the current user from the collection of users inside the StudentPool. 

I tried: 
- setting a scope 
- deleting the user.id from the studentpoolarray 
- deleting the instance of current User from the collection @active_students_in_pool based on the user ID. However can't access it. 
## What is link to your PR?
https://github.com/mrjln/matchingstudents/
## What is the expected outcome?
see question
## What is the actual outcome?
still the complete collection of students (without the admins, but with the current user)

**Comment by michfarr** [comment]
A couple of things I noticed in your models that may be contributing :)

Not equal to what, exactly ❓
https://github.com/mrjln/matchingstudents/blob/master/app/models/user.rb#L24

Is this in the right model ⁉️
https://github.com/mrjln/matchingstudents/blob/master/app/models/user.rb#L9
