### ISSUE TITLE
rspec returns: undefined method `create' 

### ISSUE THREAD

**Issue by aaartvark** [Codaisseur/TicketSystem#9]
AlbertAartsen

I cant figure out what I'm doing wrong. My code looks very much like code I used elsewhere, but it does not work.

describe "User admin attribute true" do
      let(:user) { create :user,
          email: "aaa@user.com",
          password: "abcd1234",
          admin: true
        }

      it "has admin attribute set to true" do
        expect(user.admin).to eq true
      end
    end

not in my repo yet
WANT: expect(user.admin).to eq true

GET: NoMethodError:
       undefined method `create' for #<RSpec::ExampleGroups::User::UserAdminAttributeTrue:0x007fa7db2752d8>
     # ./spec/models/user_spec.rb:13:in `block (3 levels) in <top (required)>'
     # ./spec/models/user_spec.rb:20:in `block (3 levels) in <top (required)>'

**Comment by michfarr** [comment]
Do you have `FactoryGirl` gem enabled for the test group in your `Gemfile`?

**Comment by aaartvark** [comment]
Yes I do, it works for other tests

**Comment by michfarr** [comment]
If you add a support file

```ruby
# spec/support/factory_bot.rb
RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods
end
```

and insure you have the files from your `spec/support` directory required, as well as the factories (usually around line 25 or so)
```ruby
# spec/rails_helper.rb
Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
Dir[Rails.root.join('spec/factories/**/*.rb')].each { |f| require f }
```

then everything should work fine for you and you'll not have to call the create method on FactoryGirl (`FactoryGirl.create(:user)`) and will instead be able to use it (`create(:user)`).

**Comment by arnoFleming** [comment]
And next time: Use the template provided in the issue !
